---
dataset: "dataset_test"
#accession_ids_file: "resources/list_of_accession_ids.txt"
gtdb_version: "202"
gtdb_subversion: "0"
gtdb_base_url: "https://data.ace.uq.edu.au/public/gtdb/data/releases/"
all_proteomes_outdir: "resources/all_proteomes"
all_genomes_outdir: "resources/all_genomes"
# manually add taxa information that is not present in GTDB's taxonomy file
manually_add_taxa_file: "resources/manually_add_taxa.txt"
diamond:
  threads: 16
  evalue_cut: 1e-5
  # percent:
  cov_cut: 50 
mcl:
  inflation: [1.4, 1.8, 2.0]
  # memory in MB, 20 GB was not enough, setting to 100 GB
  memory: 100000
  # runtime in minutes (1 day = 1440 min)
  runtime: 1440
eggnog:
  threads: 60
mafft:
  threads: 4
