configfile: "config/config.yaml"

import glob

def get_all_genomes_protein_parts_annotations(wildcards):
    annot = []
    for file in sorted(glob.glob("resources/{}/*.faa".format(wildcards.dataset))):
        annot.append(file.replace(".faa", ".emapper.annotations").replace("resources", "results").replace(wildcards.dataset, f"{wildcards.dataset}/eggnog"))
    return annot

rule all:
    input:
        "results/{}/annotations.emapper.annotations".format(config["dataset"]),
        "results/{}/eggnog_cogonly_genome2cogcounts.csv".format(config["dataset"]),
        "results/{}/eggnog_allcat_genome2cogcounts.csv".format(config["dataset"])

rule download_eggnog_diamond_database:
    output:
        "resources/eggnog_diamond_db/eggnog.db",
        "resources/eggnog_diamond_db/eggnog_proteins.dmnd",
        "resources/eggnog_diamond_db/eggnog.taxa.db",
        "resources/eggnog_diamond_db/eggnog.taxa.db.traverse.pkl"
    params:
        outdir="resources/eggnog_diamond_db"
    shell:
        """
        mkdir -p {params.outdir}
        download_eggnog_data.py -y -f --data_dir {params.outdir}
        """

rule eggnog_mapper:
    input:
        query="resources/{dataset}/all_genomes_protein.part{part}.faa",
        db="resources/eggnog_diamond_db/eggnog.db",
        dmnd="resources/eggnog_diamond_db/eggnog_proteins.dmnd",
        taxadb="resources/eggnog_diamond_db/eggnog.taxa.db",
        pkl="resources/eggnog_diamond_db/eggnog.taxa.db.traverse.pkl"
    output:
        "results/{dataset}/eggnog/all_genomes_protein.part{part}.emapper.annotations",
        "results/{dataset}/eggnog/all_genomes_protein.part{part}.emapper.hits",
        "results/{dataset}/eggnog/all_genomes_protein.part{part}.emapper.seed_orthologs",
    threads: config["eggnog"]["threads"]
    resources:
        mem_mb_per_cpu=1500,
        runtime=5760
    params:
        mode="diamond",
        outputprefix="results/{dataset}/eggnog/all_genomes_protein.part{part}",
        db="resources/eggnog_diamond_db"
    shell:
        """
        emapper.py -i {input.query} --cpu {threads} --data_dir {params.db} -m {params.mode} --output {params.outputprefix} --override --dbmem
        """

rule merge_annotations:
    input:
        get_all_genomes_protein_parts_annotations
    output:
        "results/{dataset}/annotations.emapper.annotations"
    shell:
        """
        FIRST=1
        for f in {input:q}; do
            if [ "$FIRST" -eq "1" ]; then
                cat $f > {output}
                FIRST=0
            else
                tail -n +6 $f >> {output}
            fi
        done
        """

rule create_eggnog_cog_counts_table_cogonly:
    input:
        eggnog_annotations="results/{dataset}/annotations.emapper.annotations",
        genome_to_abbrev="resources/{dataset}/genome2abbrev.csv"
    output:
        "results/{dataset}/eggnog_cogonly_genome2cogcounts.csv",
        "results/{dataset}/eggnog_cogonly_cog2genes.list"
    params:
        output_prefix="results/{dataset}/eggnog_cogonly",
        column_name_for_abbrev="short"
    resources:
        mem_mb_per_cpu=53600,
        runtime=1440
    shell:
        """
        scripts/generate_counts_table.py -e {input.eggnog_annotations} -o {params.output_prefix} -m {input.genome_to_abbrev} --map-col-eggnog {params.column_name_for_abbrev}
        """
 
rule create_eggnog_cog_counts_table_allcat:
    input:
        eggnog_annotations="results/{dataset}/annotations.emapper.annotations",
        genome_to_abbrev="resources/{dataset}/genome2abbrev.csv"
    output:
        "results/{dataset}/eggnog_allcat_genome2cogcounts.csv",
        "results/{dataset}/eggnog_allcat_cog2genes.list"
    params:
        output_prefix="results/{dataset}/eggnog_allcat",
        column_name_for_abbrev="short"
    resources:
        mem_mb_per_cpu=306800,
        runtime=1440
    shell:
        """
        scripts/generate_counts_table.py -e {input.eggnog_annotations} -o {params.output_prefix} -m {input.genome_to_abbrev} --map-col-eggnog {params.column_name_for_abbrev} --all
        """
