configfile: "config/config.yaml"

import glob
import os
def get_phylobayes_per_fam_result_files(wildcards):
    msas=[]
    for file in glob.glob("resources/{}/top_families/*.phylip".format(config["dataset"])):
        base = os.path.basename(file).split(".phylip")[0]
        for chain in config["phylobayes"]["chains"]:
            msas.append("results/{}/phylobayes_per_fam/{}_{}_{}_chain{}.done".format(config["dataset"], base, config["phylobayes"]["model"], config["phylobayes"]["exch"], chain))
    return msas

def get_iqtree_per_fam_result_files(wildcards):
    msas=[]
    for file in glob.glob("resources/{}/top_families/*.phylip".format(config["dataset"])):
        base = os.path.basename(file).split(".phylip")[0]
        msas.append("results/{}/iqtree_per_fam/{}_{}.iqtree".format(config["dataset"], base, config["iqtree"]["model"]))
    return msas

rule all:
    input:
        get_phylobayes_per_fam_result_files,
        expand("results/{dataset}/phylobayes/concatenated_{model}_{exch}_chain{chain}.done", dataset=config["dataset"], model=config["phylobayes"]["model"], exch=config["phylobayes"]["exch"], chain=config["phylobayes"]["chains"]),
        expand("results/{dataset}/iqtree/concatenated.iqtree", dataset=config["dataset"]),
        expand("results/{dataset}/alerax_iqtree/per_fam_likelihoods.txt", dataset=config["dataset"]),
        expand("results/{dataset}/alerax_pb/per_fam_likelihoods.txt", dataset=config["dataset"])

rule start_phylobayes_perfamily:
    input:
        "resources/{dataset}/top_families/{msa}.phylip" 
    output:
        "results/{dataset}/phylobayes_per_fam/{msa}_{model}_{exch}_chain{chain}.done"
    threads: 1
    resources:
        mem_mb_per_cpu=4000,
        runtime=config["phylobayes"]["runtime"],
        mpi="mpirun",
        tasks=config["phylobayes"]["tasks"],
        mpimodule=config["openmpi_module_name"]
    params:
        output_prefix="results/{dataset}/phylobayes_per_fam/{msa}_{model}_{exch}_chain{chain}",
        target_samples=config["phylobayes"]["target_samples"]
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for phylobayes if set
        if [ ! -z "{config[phylobayes][module_name]}" ]; then
            module load {config[phylobayes][module_name]}
        fi
        # executable path for Phylobayes
        PB="pb_mpi"
        if [ ! -z "{config[phylobayes][path]}" ]; then
            PB="{config[phylobayes][path]}"
        fi

        if [ -f {params.output_prefix}.treelist ]; then
            SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
            if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
               touch {output}
               exit 0
            fi
        fi

        # we didn't reach sufficient sampling yet
        if [ -f {params.output_prefix}.run ]; then
            {resources.mpi} -np {resources.tasks} $PB {params.output_prefix}
        else
            {resources.mpi} -np {resources.tasks} $PB -d {input} -{wildcards.model} -{wildcards.exch} -x 1 {params.target_samples} {params.output_prefix}
        fi

        SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
        if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
            touch {output}
            exit 0
        fi
        """

rule start_iqtree_perfamily:
    input:
        "resources/{dataset}/top_families/{msa}.phylip" 
    output:
        protected("results/{dataset}/iqtree_per_fam/{msa}_{model}.iqtree")
    threads: config["iqtree"]["threads"]
    resources:
        mem_mb_per_cpu=config["iqtree"]["mem"],
        runtime=config["iqtree"]["runtime"]
    shell:
        """
	# load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for iqtree if set
        if [ ! -z "{config[iqtree][module_name]}" ]; then
            module load {config[iqtree][module_name]}
        fi
        # executable path for IQTree
        IQTREE="iqtree"
        if [ ! -z "{config[iqtree][path]}" ]; then
            IQTREE="{config[iqtree][path]}"
        fi

        BASE=`echo "{output}" | sed 's/\\.iqtree//'`
        $IQTREE -s {input} -m {wildcards.model} -B 5000 -wbtl -nt {threads} --prefix $BASE

        if [ -f "{output}" ]; then
            exit 0
        fi
        """


rule start_iqtree_on_concatenate:
    input:
        "resources/{dataset}/concatenated.fa"
    output:
        protected("results/{dataset}/iqtree/concatenated.iqtree")
    threads: config["iqtree"]["threads"]
    resources:
        mem_mb_per_cpu=config["iqtree"]["mem"],
        runtime=config["iqtree"]["runtime"]
    params:
        output_prefix="results/{dataset}/iqtree/concatenated"
    shell:
        """
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for iqtree if set
        if [ ! -z "{config[iqtree][module_name]}" ]; then
            module load {config[iqtree][module_name]}
        fi
        # executable path for IQTree
        IQTREE="iqtree"
        if [ ! -z "{config[iqtree][path]}" ]; then
            IQTREE="{config[iqtree][path]}"
        fi

        $IQTREE -s {input} -m {config[iqtree][model]} -B 5000 -wbtl -nt {threads} --prefix {params.output_prefix}

        if [ -f {params.output_prefix}.iqtree ]; then
            exit 0
        fi
        """

rule start_phylobayes_on_concatenate:
    input:
        "resources/{dataset}/concatenated.phylip"
    output:
        "results/{dataset}/phylobayes/concatenated_{model}_{exch}_chain{chain}.done"
    threads: 1
    resources:
        mem_mb_per_cpu=8000,
        runtime=1440,
        mpi="mpirun",
        tasks=config["phylobayes"]["tasks_concatenated"],
        mpimodule=config["openmpi_module_name"]
    params:
        output_prefix="results/{dataset}/phylobayes/concatenated_{model}_{exch}_chain{chain}",
        target_samples=config["phylobayes"]["target_samples_concatenated"]
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for phylobayes if set
        if [ ! -z "{config[phylobayes][module_name]}" ]; then
            module load {config[phylobayes][module_name]}
        fi
        # executable path for Phylobayes
        PB="pb_mpi"
        if [ ! -z "{config[phylobayes][path]}" ]; then
            PB="{config[phylobayes][path]}"
        fi

        if [ -f {params.output_prefix}.treelist ]; then
            SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
            if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
               touch {output}
               exit 0
            fi
        fi

        # we didn't reach sufficient sampling yet
        if [ -f {params.output_prefix}.run ]; then
            {resources.mpi} -np {resources.tasks} $PB {params.output_prefix}
        else
            {resources.mpi} -np {resources.tasks} $PB -d {input} -{wildcards.model} -{wildcards.exch} -x 1 {params.target_samples} {params.output_prefix}
        fi

        SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
        if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
            touch {output}
            exit 0
        fi
        """

rule cut_burnin_from_phylobayes_treelist:
    input:
        get_phylobayes_per_fam_result_files
    output:
        directory("results/{dataset}/phylobayes_burnin_cut/")
    params:
        inputdir="results/{dataset}/phylobayes_per_fam/"
    shell:
        """
        if [ ! -d "{output}" ]; then
            mkdir {output}
        fi
        for f in {params.inputdir}/*chain{config[phylobayes][chains][0]}.treelist; do
            BASE=`basename -s .treelist $f`
            tail -n +{config[phylobayes][burnin]} $f > {output}/${{BASE}}.treelist
        done
        """

rule generate_alerax_pb_family_file:
    input:
        "results/{dataset}/phylobayes_burnin_cut"
    output:
        "results/{dataset}/alerax_pb/families.txt"
    shell:
        "scripts/generate_families.py -i {input} -o {output}"


rule generate_alerax_iqtree_family_file:
    input:
        get_iqtree_per_fam_result_files
    output:
        "results/{dataset}/alerax_iqtree/families.txt"
    params:
        inputdir="results/{dataset}/iqtree_per_fam/"
    shell:
        "scripts/generate_families.py -i {params.inputdir} -o {output}"


rule start_alerax_pb:
    input:
        "results/{dataset}/alerax_pb/families.txt"
    output:
        "results/{dataset}/alerax_pb/per_fam_likelihoods.txt"
    resources:
        tasks=config["alerax"]["tasks"],
        mpi="mpirun",
        mpimodule=config["openmpi_module_name"]
    params:
        outputdir="results/{dataset}/alerax_pb/"
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for AleRax if set
        if [ ! -z "{config[alerax][module_name]}" ]; then
            module load {config[alerax][module_name]}
        fi
        # executable path for AleRax
        ALERAX="alerax"
        if [ ! -z "{config[alerax][path]}" ]; then
            ALERAX="{config[alerax][path]}"
        fi

        {resources.mpi} -np {resources.tasks} $ALERAX \
        --families {input} \
        --rec-model UndatedDTL \
        --species-tree-search HYBRID \
        -s MiniNJ \
        --transfer-constraint PARENTS \
        --prefix {params.outputdir}
        """

rule start_alerax_iqtree:
    input:
        "results/{dataset}/alerax_iqtree/families.txt"
    output:
        "results/{dataset}/alerax_iqtree/per_fam_likelihoods.txt"
    params:
        outputdir="results/{dataset}/alerax_iqtree/"
    resources:
        tasks=config["alerax"]["tasks"],
        mpi="mpirun",
        mpimodule=config["openmpi_module_name"]
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for AleRax if set
        if [ ! -z "{config[alerax][module_name]}" ]; then
            module load {config[alerax][module_name]}
        fi
        # executable path for AleRax
        ALERAX="alerax"
        if [ ! -z "{config[alerax][path]}" ]; then
            ALERAX="{config[alerax][path]}"
        fi

        {resources.mpi} -np {resources.tasks} $ALERAX \
        --families {input} \
        --rec-model UndatedDTL \
        --species-tree-search HYBRID \
        -s MiniNJ \
        --transfer-constraint PARENTS \
        --prefix {params.outputdir}
        """

