configfile: "config/config.yaml"

import glob
import os

# Mirror the clustering mode from Stage 1 so named rules only request the
# cluster types that were actually produced in Stage 2.
_CLUSTERS = ["eggnog"] if config.get("clustering", "eggnog") == "eggnog" else ["mcl", "eggnog"]

def get_phylobayes_per_fam_result_files(wildcards):
    msas=[]
    for file in glob.glob("resources/{}/{}/top_families/*.phylip".format(wildcards.dataset, wildcards.cluster)):
        base = os.path.basename(file).split(".phylip")[0]
        for chain in config["phylobayes"]["chains"]:
            msas.append("results/{}/{}/phylobayes_per_fam/{}_{}_{}_chain{}.done".format(wildcards.dataset, wildcards.cluster, base, config["phylobayes"]["model"], config["phylobayes"]["exch"], chain))
    return msas

def get_iqtree_per_fam_result_files(wildcards):
    msas=[]
    for file in glob.glob("resources/{}/{}/top_families/*.phylip".format(wildcards.dataset, wildcards.cluster)):
        base = os.path.basename(file).split(".phylip")[0]
        #if base != "gf70799":
        msas.append("results/{}/{}/iqtree_per_fam/{}_{}.done".format(wildcards.dataset, wildcards.cluster, base, config["iqtree"]["model"]))
    return msas

rule all:
    input:
        rules.per_family_all.input,
        rules.concat_all.input,
        rules.alerax_all.input,

# Named targets used by the governor script to run stages independently.
rule per_family_all:
    input:
        expand("results/{dataset}/{cluster}/phylobayes_burnin_cut", dataset=config["dataset"], cluster=_CLUSTERS),
        expand("results/{dataset}/{cluster}/alerax_pb/families.txt", dataset=config["dataset"], cluster=_CLUSTERS),
        expand("results/{dataset}/{cluster}/alerax_iqtree/families.txt", dataset=config["dataset"], cluster=_CLUSTERS),

rule concat_all:
    input:
        expand("results/{dataset}/{cluster}/phylobayes/concatenated_universality_{model}_{exch}_chain{chain}.done", dataset=config["dataset"], cluster=_CLUSTERS, model=config["phylobayes"]["model"], exch=config["phylobayes"]["exch"], chain=config["phylobayes"]["chains"]),
        expand("results/{dataset}/{cluster}/iqtree/concatenated.universality.iqtree", dataset=config["dataset"], cluster=_CLUSTERS),

rule alerax_all:
    input:
        expand("results/{dataset}/{cluster}/alerax_iqtree/per_fam_likelihoods.txt", dataset=config["dataset"], cluster=_CLUSTERS),
        expand("results/{dataset}/{cluster}/alerax_pb/per_fam_likelihoods.txt", dataset=config["dataset"], cluster=_CLUSTERS),

rule start_phylobayes_perfamily:
    input:
        "resources/{dataset}/{cluster}/top_families/{msa}.phylip" 
    output:
        "results/{dataset}/{cluster}/phylobayes_per_fam/{msa}_{model}_{exch}_chain{chain}.done"
    threads: 1
    resources:
        mem_mb_per_cpu=4000,
        runtime=config["phylobayes"]["runtime"],
        mpi="mpirun",
        tasks=config["phylobayes"]["tasks"],
        mpimodule=config["openmpi_module_name"]
    params:
        output_prefix="results/{dataset}/{cluster}/phylobayes_per_fam/{msa}_{model}_{exch}_chain{chain}",
        target_samples=config["phylobayes"]["target_samples"]
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for phylobayes if set
        if [ ! -z "{config[phylobayes][module_name]}" ]; then
            module load {config[phylobayes][module_name]}
        fi
        # executable path for Phylobayes
        PB="pb_mpi"
        if [ ! -z "{config[phylobayes][path]}" ]; then
            PB="{config[phylobayes][path]}"
        fi

        if [ -f {params.output_prefix}.treelist ]; then
            SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
            if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
               touch {output}
               exit 0
            fi
        fi

        # we didn't reach sufficient sampling yet
        if [ -f {params.output_prefix}.run ]; then
            {resources.mpi} -np {resources.tasks} $PB {params.output_prefix}
        else
            {resources.mpi} -np {resources.tasks} $PB -d {input} -{wildcards.model} -{wildcards.exch} -x 1 {params.target_samples} {params.output_prefix}
        fi

        SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
        if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
            touch {output}
            exit 0
        fi
        """

rule start_iqtree_perfamily:
    input:
        "resources/{dataset}/{cluster}/top_families/{msa}.phylip" 
    output:
        "results/{dataset}/{cluster}/iqtree_per_fam/{msa}_{model}.done"
    threads: config["iqtree"]["threads"]
    resources:
        mem_mb_per_cpu=config["iqtree"]["mem"],
        runtime=config["iqtree"]["runtime"]
    shell:
        """
	# load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for iqtree if set
        if [ ! -z "{config[iqtree][module_name]}" ]; then
            module load {config[iqtree][module_name]}
        fi
        # executable path for IQTree
        IQTREE="iqtree"
        if [ ! -z "{config[iqtree][path]}" ]; then
            IQTREE="{config[iqtree][path]}"
        fi
        
        OUTPUT_PREFIX=`echo "{output}" | sed 's/\\.done//'`

	if [ -f ${{OUTPUT_PREFIX}}.iqtree ] && [ -f ${{OUTPUT_PREFIX}}.ufboot ] && [ -f ${{OUTPUT_PREFIX}}.done ]; then
            exit 0
        else
            $IQTREE -s {input} -m {wildcards.model} -B 5000 -wbtl -nt {threads} --prefix $OUTPUT_PREFIX -safe
        fi

        if [ -f ${{OUTPUT_PREFIX}}.iqtree ] && [ -f ${{OUTPUT_PREFIX}}.ufboot ]; then
            touch {output}
            exit 0
        fi
        """


rule start_iqtree_on_concatenate:
    input:
        "resources/{dataset}/{cluster}/concatenated.universality.fa"
    output:
        "results/{dataset}/{cluster}/iqtree/concatenated.universality.done"
    threads: config["iqtree"]["threads_concatenated"]
    resources:
        mem_mb_per_cpu=config["iqtree"]["mem"],
        runtime=config["iqtree"]["runtime"]
    shell:
        """
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for iqtree if set
        if [ ! -z "{config[iqtree][module_name]}" ]; then
            module load {config[iqtree][module_name]}
        fi
        # executable path for IQTree
        IQTREE="iqtree"
        if [ ! -z "{config[iqtree][path]}" ]; then
            IQTREE="{config[iqtree][path]}"
        fi

        OUTPUT_PREFIX=`echo "{output}" | sed 's/\\.done//'`

	if [ -f ${{OUTPUT_PREFIX}}.iqtree ] && [ -f ${{OUTPUT_PREFIX}}.ufboot ] && [ -f ${{OUTPUT_PREFIX}}.done ]; then
            exit 0
        else
            $IQTREE -s {input} -m {config[iqtree][model]} -B 5000 -wbtl -nt {threads} --prefix $OUTPUT_PREFIX -safe
        fi

        if [ -f ${{OUTPUT_PREFIX}}.iqtree ] && [ -f ${{OUTPUT_PREFIX}}.ufboot ]; then
            touch {output}
            exit 0
        fi
        """

rule start_phylobayes_on_concatenate:
    input:
        "resources/{dataset}/{cluster}/concatenated.universality.phylip"
    output:
        "results/{dataset}/{cluster}/phylobayes/concatenated_universality_{model}_{exch}_chain{chain}.done"
    threads: 1
    resources:
        mem_mb_per_cpu=8000,
        runtime=config["phylobayes"]["runtime"],
        mpi="mpirun",
        tasks=config["phylobayes"]["tasks_concatenated"],
        mpimodule=config["openmpi_module_name"]
    params:
        output_prefix="results/{dataset}/{cluster}/phylobayes/concatenated_universality_{model}_{exch}_chain{chain}",
        target_samples=config["phylobayes"]["target_samples_concatenated"]
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for phylobayes if set
        if [ ! -z "{config[phylobayes][module_name]}" ]; then
            module load {config[phylobayes][module_name]}
        fi
        # executable path for Phylobayes
        PB="pb_mpi"
        if [ ! -z "{config[phylobayes][path]}" ]; then
            PB="{config[phylobayes][path]}"
        fi

        if [ -f {params.output_prefix}.treelist ]; then
            SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
            if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
               touch {output}
               exit 0
            fi
        fi

        # we didn't reach sufficient sampling yet
        if [ -f {params.output_prefix}.run ]; then
            {resources.mpi} -np {resources.tasks} $PB {params.output_prefix}
        else
            {resources.mpi} -np {resources.tasks} $PB -d {input} -{wildcards.model} -{wildcards.exch} -x 1 {params.target_samples} {params.output_prefix}
        fi

        SAMPLES=`wc -l {params.output_prefix}.treelist | sed -E 's/\\s+/ /g' | cut -d " " -f 1`
        if [ "$SAMPLES" -ge "{params.target_samples}" ]; then
            touch {output}
            exit 0
        fi
        """

rule cut_burnin_from_phylobayes_treelist:
    input:
        get_phylobayes_per_fam_result_files
    output:
        directory("results/{dataset}/{cluster}/phylobayes_burnin_cut/")
    params:
        inputdir="results/{dataset}/{cluster}/phylobayes_per_fam/"
    shell:
        """
        if [ ! -d "{output}" ]; then
            mkdir {output}
        fi
        for f in {params.inputdir}/*chain{config[phylobayes][chains][0]}.treelist; do
            BASE=`basename -s .treelist $f`
            tail -n +{config[phylobayes][burnin]} $f > {output}/${{BASE}}.treelist
        done
        """

rule generate_alerax_pb_family_file:
    input:
        "results/{dataset}/{cluster}/phylobayes_burnin_cut"
    output:
        "results/{dataset}/{cluster}/alerax_pb/families.txt"
    shell:
        "scripts/generate_families.py -i {input} -o {output}"


rule generate_alerax_iqtree_family_file:
    input:
        get_iqtree_per_fam_result_files
    output:
        "results/{dataset}/{cluster}/alerax_iqtree/families.txt"
    params:
        inputdir="results/{dataset}/{cluster}/iqtree_per_fam/"
    shell:
        "scripts/generate_families.py -i {params.inputdir} -o {output}"


rule start_alerax_pb:
    input:
        "results/{dataset}/{cluster}/alerax_pb/families.txt"
    output:
        "results/{dataset}/{cluster}/alerax_pb/per_fam_likelihoods.txt"
    resources:
        tasks=config["alerax"]["tasks"],
        mpi="mpirun",
        mpimodule=config["openmpi_module_name"],
        runtime=config["alerax"]["runtime"]
    params:
        outputdir="results/{dataset}/{cluster}/alerax_pb/",
        # Use a user-provided species tree if given, otherwise let AleRax infer one.
        species_tree=config.get("species_tree", "MiniNJ")
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for AleRax if set
        if [ ! -z "{config[alerax][module_name]}" ]; then
            module load {config[alerax][module_name]}
        fi
        # executable path for AleRax
        ALERAX="alerax"
        if [ ! -z "{config[alerax][path]}" ]; then
            ALERAX="{config[alerax][path]}"
        fi

        {resources.mpi} -np {resources.tasks} $ALERAX \
        --families {input} \
        --rec-model UndatedDTL \
        --species-tree-search HYBRID \
        -s {params.species_tree} \
        --transfer-constraint PARENTS \
        --prefix {params.outputdir}
        """

rule start_alerax_iqtree:
    input:
        "results/{dataset}/{cluster}/alerax_iqtree/families.txt"
    output:
        "results/{dataset}/{cluster}/alerax_iqtree/per_fam_likelihoods.txt"
    params:
        outputdir="results/{dataset}/{cluster}/alerax_iqtree/",
        # Use a user-provided species tree if given, otherwise let AleRax infer one.
        species_tree=config.get("species_tree", "MiniNJ")
    resources:
        tasks=config["alerax"]["tasks"],
        mpi="mpirun",
        mpimodule=config["openmpi_module_name"],
        runtime=config["alerax"]["runtime"]
    shell:
        """
        # load modules necessary for mpi
        if [ ! -z "{resources.mpimodule}" ]; then
            module load {resources.mpimodule}
        fi
        # load other sources of modules if set
        if [ ! -z "{config[extra_modules]}" ]; then
            module use {config[extra_modules]}
        fi
        # load module for AleRax if set
        if [ ! -z "{config[alerax][module_name]}" ]; then
            module load {config[alerax][module_name]}
        fi
        # executable path for AleRax
        ALERAX="alerax"
        if [ ! -z "{config[alerax][path]}" ]; then
            ALERAX="{config[alerax][path]}"
        fi

        {resources.mpi} -np {resources.tasks} $ALERAX \
        --families {input} \
        --rec-model UndatedDTL \
        --species-tree-search HYBRID \
        -s {params.species_tree} \
        --transfer-constraint PARENTS \
        --prefix {params.outputdir}
        """

