configfile: "config/config.yaml"

def get_accession_ids_file(wildcards):
    return "resources/{}/{}".format(wildcards.dataset, config["accession_ids_file"])

rule all:
    input:
        "resources/bac120_taxonomy_r{}.tsv".format(config["gtdb_version"]),
        "resources/{}/selected_genomes_protein".format(config["dataset"]),
        "results/{}/genome2abbrev.csv".format(config["dataset"]),
        expand("results/{dataset}/mcl_clusters_I{inf}.txt", dataset=config["dataset"], inf=config["mcl"]["inflation"]),
        "results/{}/eggnog/annotations.emapper.annotations".format(config["dataset"]),
        expand("results/{dataset}/mcl/{inf}", dataset=config["dataset"], inf=config["mcl"]["inflation"]),
        "results/{}/cog_clusters".format(config["dataset"]),
        "results/{}/eggnog_cog_counts_table.csv".format(config["dataset"])

rule get_all_genomes_protein:
    output:
        r"resources/all_genomes_protein{gtdb_version,\d+}.tar.gz",
    shell:
        """
        if curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/genomic_files_reps/gtdb_proteins_aa_reps_r{config[gtdb_version]}.tar.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/genomic_files_reps/gtdb_proteins_aa_reps_r{config[gtdb_version]}.tar.gz' -O {output}
        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/gtdb_r{config[gtdb_version]}_rep_genomes.protein.faa.tar.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/gtdb_r{config[gtdb_version]}_rep_genomes.protein.faa.tar.gz' -O {output}
        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/genomic_files_reps/gtdb_r{config[gtdb_version]}_rep_genomes.protein.faa.tar.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/genomic_files_reps/gtdb_r{config[gtdb_version]}_rep_genomes.protein.faa.tar.gz' -O {output}
        else
            echo "Proteomes not found on GTDB server"
            exit -111
        fi
        """

rule get_all_genomes_na:
    output:
        r"resources/all_genomes_na{gtdb_version,\d+}.tar.gz"
    shell:
        """
        if curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/genomic_files_reps/gtdb_genomes_reps_r{config[gtdb_version]}.tar.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/genomic_files_reps/gtdb_genomes_reps_r{config[gtdb_version]}.tar.gz' -O {output}
        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/gtdb_r{config[gtdb_version]}.tar.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/gtdb_r{config[gtdb_version]}.tar.gz' -O {output}
        else
            echo "Genomes not found on GTDB server"
            exit -111
        fi
        """

rule extract_all_genomes_protein:
    input:
        "resources/all_genomes_protein{gtdb_version}.tar.gz"
    output:
        directory(r"resources/all_genomes_protein{gtdb_version,\d+}")
    shell:
        """
        mkdir {output}
        tar -xzf {input} -C {output} --strip-components=1
        """

rule extract_all_genomes_na:
    input:
        "resources/all_genomes_na{gtdb_version}.tar.gz"
    output:
        directory(r"resources/all_genomes_na{gtdb_version,\d+}")
    shell:
        """
        mkdir {output}
        tar -xzf {input} -C {output} --strip-components=1
        """

rule select_genomes_protein:
    input:
        get_accession_ids_file,
        "resources/all_genomes_protein{gtdbversion}".format(gtdbversion=config["gtdb_version"])
    output:
        directory("resources/{dataset}/selected_genomes_protein")
    shell:
        "scripts/select_genomes_protein.sh {input[0]} {input[1]} {output}"

rule select_genomes_na:
    input:
        get_accession_ids_file,
        "resources/all_genomes_na{gtdbversion}".format(gtdbversion=config["gtdb_version"])
    output:
        directory("resources/{dataset}/selected_genomes_na")
    shell:
        "scripts/select_genomes_na.sh {input[0]} {input[1]} {output}"

rule get_bacterial_taxonomy_file:
    output:
        "resources/bac120_taxonomy_r{}.tsv.gz".format(config["gtdb_version"])
    shell:
        """
        if curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac120_taxonomy_r{config[gtdb_version]}.tsv.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac120_taxonomy_r{config[gtdb_version]}.tsv.gz' -O {output}

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac_taxonomy_r{config[gtdb_version]}.tsv.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac_taxonomy_r{config[gtdb_version]}.tsv.gz' -O {output}

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac120_taxonomy_r{config[gtdb_version]}.tsv' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac120_taxonomy_r{config[gtdb_version]}.tsv' -O {output}
            mv {output} resources/bac120_taxonomy_r{config[gtdb_version]}.tsv
            gzip resources/bac120_taxonomy_r{config[gtdb_version]}.tsv

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac_taxonomy_r{config[gtdb_version]}.tsv'; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/bac_taxonomy_r{config[gtdb_version]}.tsv' -O {output}
            mv {output} resources/bac120_taxonomy_r{config[gtdb_version]}.tsv
            gzip resources/bac120_taxonomy_r{config[gtdb_version]}.tsv

        else
            echo "GTDB taxonomy file could not be found"
            exit -111
        fi
        """

rule get_archaeal_taxonomy_file:
    output:
        "resources/ar53_taxonomy_r{}.tsv.gz".format(config["gtdb_version"])
    shell:
        """
        if curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar53_taxonomy_r{config[gtdb_version]}.tsv.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar53_taxonomy_r{config[gtdb_version]}.tsv.gz' -O {output}

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar_taxonomy_r{config[gtdb_version]}.tsv.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar_taxonomy_r{config[gtdb_version]}.tsv.gz' -O {output}

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar122_taxonomy_r{config[gtdb_version]}.tsv.gz' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar122_taxonomy_r{config[gtdb_version]}.tsv.gz' -O {output}

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar53_taxonomy_r{config[gtdb_version]}.tsv' >/dev/null 2>&1; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar53_taxonomy_r{config[gtdb_version]}.tsv' -O {output}
            mv {output} resources/ar53_taxonomy_r{config[gtdb_version]}.tsv
            gzip resources/ar53_taxonomy_r{config[gtdb_version]}.tsv

        elif curl -f '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar_taxonomy_r{config[gtdb_version]}.tsv'; then
            wget '{config[gtdb_base_url]}release{config[gtdb_version]}/{config[gtdb_version]}.{config[gtdb_subversion]}/ar_taxonomy_r{config[gtdb_version]}.tsv' -O {output}
            mv {output} resources/ar53_taxonomy_r{config[gtdb_version]}.tsv
            gzip resources/ar53_taxonomy_r{config[gtdb_version]}.tsv

        else
            echo "GTDB taxonomy file could not be found"
            exit -111
        fi
        """

rule unzip_bacterial_taxonomy_file:
    input:
        "resources/bac120_taxonomy_r{}.tsv.gz".format(config["gtdb_version"])
    output:
        "resources/bac120_taxonomy_r{}.tsv".format(config["gtdb_version"])
    shell:
        "gzip -d {input}"

rule unzip_archaeal_taxonomy_file:
    input:
        "resources/ar53_taxonomy_r{}.tsv.gz".format(config["gtdb_version"])
    output:
        "resources/ar53_taxonomy_r{}.tsv".format(config["gtdb_version"])
    shell:
        "gzip -d {input}"

rule create_genome2taxa:
    input:
        get_accession_ids_file,
        "resources/bac120_taxonomy_r{}.tsv".format(config["gtdb_version"]),
        "resources/ar53_taxonomy_r{}.tsv".format(config["gtdb_version"])
    output:
        "results/{dataset}/genome2taxa.csv"
    params:
        manual_taxa="resources/{}/{}".format(config["dataset"], config["manually_add_taxa_file"])
    shell:
        """
        #REGEXP=`tr '\\n' '|' < {input[0]} | sed 's/|$//'`
        #grep -E "$REGEXP" {input[1]} | sed -E 's/\\t+/,/g' > {output}
        #grep -E "$REGEXP" {input[2]} | sed -E 's/\\t+/,/g' >> {output}
        # the approach above doesn't work for big lists of accession IDs
        while read LINE; do
             RES=`grep "$LINE" {input[1]} || echo ""`
             if [ -z "$RES" ]; then
                 RES=`grep "$LINE" {input[2]} || echo ""`
             fi
             if [ ! -z "$RES" ]; then
                 echo "$RES" | sed -E 's/\\t+/,/g' >> {output}
             fi
        done < {input[0]}
        if [ -s "{params.manual_taxa}" ]; then
             echo "Appending contents of file {params.manual_taxa} to {output}"
             cat {params.manual_taxa} >> {output}
        else
             echo "{params.manual_taxa} not existing or empty"
        fi
        """

rule generate_shortcodes:
    input:
        "results/{dataset}/genome2taxa.csv"
    output:
        "results/{dataset}/genome2abbrev.csv"
    shell:
        "scripts/rename_genomes.py {input} {output}"

rule rename_proteins:
    input:
        "results/{dataset}/genome2abbrev.csv",
        "resources/{dataset}/selected_genomes_protein"
    output:
        directory("results/{dataset}/genomes_protein"),
        "results/{dataset}/sequenceid_new2original.csv"
    shell:
        "scripts/rename_proteins.py --map {input[0]} --in {input[1]} --out {output[0]} -t {output[1]}"

rule cat_all_sequences:
    input:
        "results/{dataset}/genomes_protein"
    output:
        "results/{dataset}/all_genomes_protein.faa"
    shell:
        """
        #for f in {input}/*.faa; do
        #    cat $f >> {output}
        #done
        find {input}/ -iname "*.faa" -exec cat {{}} >> {output} \\;
        """

rule make_diamond_db:
    input:
        "results/{dataset}/all_genomes_protein.faa"
    output:
        "results/{dataset}/genomes_protein.dmnd"
    threads: config["diamond"]["threads"]
    shell:
        "diamond makedb --in {input} -d {output} --threads {threads}"

rule diamond_all_vs_all:
    input:
        db="results/{dataset}/genomes_protein.dmnd",
        query="results/{dataset}/all_genomes_protein.faa"
    output:
        "results/{dataset}/all_vs_all_wo_selfhits.tsv"
    resources:
        mem_mb_per_cpu=5000,
        # 1 day runtime
        runtime=1440
    threads: config["diamond"]["threads"]
    shell:
        """
        diamond blastp \
                --db     {input.db} \
                --query  {input.query} \
                --out    {output} \
                --outfmt 6 qseqid sseqid pident bitscore evalue qcovhsp scovhsp \
                --more-sensitive \
                --threads {threads}
        """

rule add_self_hits_to_diamond_all_vs_all:
    input:
        query="results/{dataset}/all_genomes_protein.faa",
        diamond="results/{dataset}/all_vs_all_wo_selfhits.tsv"
    output:
        "results/{dataset}/all_vs_all.tsv"
    shell:
        """
        cp {input.diamond} {output}
        # ---------- guarantee self-hits so singletons survive ---------- 
        # q s pident bits evalue qcov scov  (7 cols, tab-separated)
        awk '/^>/{{sub(/^>/,"",$0); printf "%s\\t%s\\t100\\t1000\\t1e-200\\t100\\t100\\n",$0,$0 }}' "{input.query}" >> "{output}"
        """


rule filter_and_convert_into_mcl_s_abc_format:
    input:
        "results/{dataset}/all_vs_all.tsv"
    output:
        "results/{dataset}/all_vs_all.abc"
    params:
        evalue_cut=config["diamond"]["evalue_cut"],
        cov_cut=config["diamond"]["cov_cut"]
    shell:
        "scripts/filter_and_convert.py -i {input} -o {output} -e {params.evalue_cut} -c {params.cov_cut}"

rule mcl_sweep:
    input:
        "results/{dataset}all_vs_all.abc"
    output:
        "results/{dataset}mcl_clusters_I{inflation}.txt"
    resources:
        mem_mb_per_cpu=config["mcl"]["memory"],
        runtime=config["mcl"]["runtime"]
    shell:
        "mcl {input} --abc -I {wildcards.inflation} -o {output}"

rule split_mcl_clusters:
    input:
        fasta="results/{dataset}/all_genomes_protein.faa",
        cluster="results/{dataset}/mcl_clusters_I{inflation}.txt"
    output:
        directory("results/{dataset}/mcl/{inflation}")
    params:
        huge_cutoff=str(int(5 * sum(1 for _ in open("resources/{}/{}".format(config["dataset"], config["accession_ids_file"])))))
    shell:
        "scripts/split_clusters.py -f {input.fasta} -c {params.huge_cutoff} -m {input.cluster} -o {output}"

rule download_eggnog_diamond_database:
    output:
        "resources/eggnog_diamond_db/eggnog.db",
        "resources/eggnog_diamond_db/eggnog.db.fieldpresence.bin",
        "resources/eggnog_diamond_db/eggnog.db.taxids.bin",
        "resources/eggnog_diamond_db/eggnog_proteins.dmnd",
        "resources/eggnog_diamond_db/eggnog.taxa.db",
        "resources/eggnog_diamond_db/eggnog.taxa.db.traverse.pkl",
        "resources/eggnog_diamond_db/go-basic.obo"
    params:
        outdir="resources/eggnog_diamond_db"
    shell:
        """
        mkdir -p {params.outdir}
        # eggnog-mapper v3 beta bug: set_data_path() validates the default site-packages/data
        # directory before --data_dir is parsed. Create it so the check passes.
        #python -c "import eggnogmapper, os; os.makedirs(os.path.join(os.path.dirname(eggnogmapper.__file__), 'data'), exist_ok=True)"
        download_eggnog_data.py -y -f --data_dir {params.outdir}
        """

# break into genomes and not all
rule eggnog_mapper:
    input:
        fasta="results/{dataset}/all_genomes_protein.faa",
        db="resources/eggnog_diamond_db/eggnog.db",
        fp="resources/eggnog_diamond_db/eggnog.db.fieldpresence.bin",
        taxids="resources/eggnog_diamond_db/eggnog.db.taxids.bin",
        dmnd="resources/eggnog_diamond_db/eggnog_proteins.dmnd",
        taxadb="resources/eggnog_diamond_db/eggnog.taxa.db",
        pkl="resources/eggnog_diamond_db/eggnog.taxa.db.traverse.pkl",
        go="resources/eggnog_diamond_db/go-basic.obo"
    output:
        "results/{dataset}/eggnog/annotations.emapper.annotations",
        "results/{dataset}/eggnog/annotations.emapper.hits",
        "results/{dataset}/eggnog/annotations.emapper.seed_orthologs",
    threads: config["eggnog"]["threads"]
    resources:
        mem_mb_per_cpu=4000,
        runtime=2880
    params:
        mode="diamond",
        outputprefix="results/{dataset}/eggnog/annotations",
        db="resources/eggnog_diamond_db"
    shell:
        """
        emapper.py -i {input.fasta} --itype proteins --cpu {threads} --data_dir {params.db} -m {params.mode} --output {params.outputprefix} --override
        """

rule cluster_into_cogs:
    input:
        eggnog_annotations="results/{dataset}/eggnog/annotations.emapper.annotations",
        fasta_dir="results/{dataset}/genomes_protein"
    output:
        directory("results/{dataset}/cog_clusters")
    params:
        huge_cutoff=str(int(5 * sum(1 for _ in open("resources/{}/{}".format(config["dataset"], config["accession_ids_file"])))))
    shell:
        """
        scripts/create_cog_clusters.py -e {input.eggnog_annotations} -f {input.fasta_dir} -o {output} -c {params.huge_cutoff} 
        """

rule create_eggnog_cog_counts_table:
    input:
        eggnog_annotations="results/{dataset}/eggnog/annotations.emapper.annotations",
        genome_to_abbrev="results/{dataset}/genome2abbrev.csv"
    output:
        "results/{dataset}/eggnog_cog_counts_table.csv"
    params:
        column_name_for_accession="accession",
        column_name_for_abbrev="short"
    shell:
        """
        scripts/generate_presence_absence_table.py -e {input.eggnog_annotations} -o {output} -m {input.genome_to_abbrev} --map-col-eggnog {params.column_name_for_abbrev} --map-col-output {params.column_name_for_accession}
        """
