configfile: "config/config.yaml"

import glob

def get_msas(wildcards):
    msas=[]
    for file in glob.glob("resources/{}/{}/*.faa".format(wildcards.dataset, wildcards.cluster)):
        msas.append(file.replace(".faa", ".trim").replace("resources", "results").replace(wildcards.cluster, wildcards.cluster+"/trimal"))
    return msas

rule all:
    input:
        expand("results/{dataset}/{cluster}/alignment_statistics.txt", dataset=config["dataset"], cluster=["mcl", "eggnog"]),
        expand("results/{dataset}/{cluster}/family_scoring.txt", dataset=config["dataset"], cluster=["mcl", "eggnog"]),
        expand("results/{dataset}/{cluster}/top_families", dataset=config["dataset"], cluster=["mcl", "eggnog"]),
        expand("results/{dataset}/{cluster}/concatenated.universality.phylip", dataset=config["dataset"], cluster=["mcl", "eggnog"]),
        expand("results/{dataset}/{cluster}/concatenated.universality.fa", dataset=config["dataset"], cluster=["mcl", "eggnog"])

rule align_msas_with_mafft:
    input:
        "resources/{dataset}/{cluster}/{msa}.faa" 
    output:
        "results/{dataset}/{cluster}/mafft/{msa}.aln"
    threads: config["mafft"]["threads"]
    resources:
        mem_mb_per_cpu=4000,
        runtime=600
    shell:
        "mafft --auto --thread {threads} {input} > {output}"

rule trim_msas_with_trimal:
    input:
        "results/{dataset}/{cluster}/mafft/{msa}.aln"
    output:
        "results/{dataset}/{cluster}/trimal/{msa}.trim"
    resources:
        mem_mb_per_cpu=3000,
        runtime=600
    shell:
        "trimal -in {input} -out {output} -gt 0.1"

rule msas_statistics:
    input:
        get_msas
    output:
        "results/{dataset}/{cluster}/alignment_statistics.txt"
    params:
        inputdir="results/{dataset}/{cluster}/trimal/"
    shell:
        "scripts/alignment_stats.py -i {params.inputdir} -o {output}"

rule msas_scoring:
    input:
        get_msas
    output:
        "results/{dataset}/{cluster}/family_scoring.txt"
    params:
        inputdir="results/{dataset}/{cluster}/trimal/"
    shell:
        "scripts/family_scoring.py -i {params.inputdir} -o {output}"

rule filter_msas:
    input:
        get_msas,
        scoring="results/{dataset}/{cluster}/family_scoring.txt"
    output:
        directory("results/{dataset}/{cluster}/filtered_by_universality")
    params:
        inputdir="results/{dataset}/{cluster}/trimal/"
    shell:
        "scripts/filter_by_universality.py -i {params.inputdir} -m {input.scoring} -o {output}"

rule concatenate_filtered_msas_fasta:
    input:
        "results/{dataset}/{cluster}/filtered_by_universality"
    output:
        "results/{dataset}/{cluster}/concatenated.universality.fa"
    shell:
        "scripts/concatenate.py -i {input} -o {output} -f fasta"

rule concatenate_filtered_msas_phylip:
    input:
        "results/{dataset}/{cluster}/filtered_by_universality"
    output:
        "results/{dataset}/{cluster}/concatenated.universality.phylip"
    shell:
        "scripts/concatenate.py -i {input} -o {output} -f phylip"

rule select_topscoring_msas_for_phylobayes:
    input:
        get_msas,
        scoring="results/{dataset}/{cluster}/family_scoring.txt"
    output:
        directory("results/{dataset}/{cluster}/top_families")
    params:
        inputdir="results/{dataset}/{cluster}/trimal/"
    shell:
        "scripts/select_topscoring_for_pb.py -i {params.inputdir} -o {output} -m {input.scoring}"
